### ISSUE TITLE
Other skins for earth (unlockables)

### ISSUE THREAD

**Issue by L3NNYY** [L3NNYY/AppGame#37]
This task will be split into many:

- [x] Change settings to unlocks

- [x] Add coin earn system when playing (per 10 score is 1 coin or something)

- [x] Coins can be spent on skins or 8-bit tracks

- [ ] Possibly add monetization to get skin
